from typing import Protocol

from services.api.domain.models import ScenarioState, TurnRecord


class SessionStore(Protocol):
    def create_session(self) -> ScenarioState: ...
    def get_session(self, session_id: str) -> ScenarioState | None: ...
    def update_session(self, session_id: str, state: ScenarioState) -> None: ...
    def append_turn(self, session_id: str, turn: TurnRecord) -> None: ...
